[env]
TERM = "xterm-256color"

[font]
    size = 12.0

    [font.bold]
        family = "FiraCode Nerd Font"
        style  = "Bold"

    [font.bold_italic]
        family = "FiraCode Nerd Font"
        style  = "Bold Italic"

    [font.glyph_offset]
        x = 0
        y = 0

    [font.italic]
        family = "FiraCode Nerd Font"
        style  = "Italic"

    [font.normal]
        family = "FiraCode Nerd Font"
        style  = "Regular"

    [font.offset]
        x = 0
        y = 0

[window]
opacity = 1
decorations = "none"
dynamic_padding = true

[window.padding]
x = 0
y = 0

[scrolling]
    history    = 10000
    multiplier = 4

[general]
import = ["~/.config/alacritty/themes/themes/blood_moon.toml"]

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Hide"
key = "H"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[cursor]
style = { shape = "Block", blinking = "On" }

